/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-04-08 18:05:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Statement;
import com.deduplication.db.ConnectionFactory;
import java.sql.Connection;

public final class Other_005fdownload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.deduplication.db.ConnectionFactory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>Prove Identity Before Download File</title>\r\n");
      out.write("	<link rel=\"favicon\" href=\"assets/images/favicon.png\">\r\n");
      out.write("	<link rel=\"stylesheet\" media=\"screen\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,700\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.css\" media=\"screen\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/da-slider.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
	if(session.getAttribute("userName")==null)
	{
		 out.print("Please login first");  
         request.getRequestDispatcher("user_signin.jsp").include(request, response);  
	}
	else
	{
	session.setAttribute("Username", session.getAttribute("userName"));
    String username=(String)session.getAttribute("userName"); 
	String filename=request.getParameter("file");
	String ownerName=request.getParameter("owner");
	session.setAttribute("file", filename);
	
	String id=null;
	String hash=null;
	String status=null;
	String filePath=null;
	
	
		id=request.getParameter("id");
		hash=request.getParameter("hash");
		status=request.getParameter("status");
		filePath=request.getParameter("filepath");
		

      out.write("\r\n");
      out.write("	<div class=\"navbar navbar-inverse\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<h4 align=\"right\"> <font color=\"red\">Welcome ");
      out.print(session.getAttribute("userName"));
      out.write("</font></h4> \r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<!-- Button for smallest screens -->\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"Index.jsp\">\r\n");
      out.write("					<h4>DEDUPLICATION</h4></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navbar-collapse collapse\">\r\n");
      out.write("				<ul class=\"nav navbar-nav pull-right mainNav\">\r\n");
      out.write("					<li class=\"active\"><a href=\"user_home.jsp\">Home</a></li>\r\n");
      out.write("					<li class=\"active\"><a href=\"file_upload.jsp\">Browse File</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"Own_files.jsp\">Own Files</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"View_files.jsp\">View Files</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"downloadRequest.jsp\">View Request</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"Profile.jsp\">Setting</a></li>\r\n");
      out.write("					<li class=\"active\"><a href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("            </ul>          \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("<div class=\"container\"  align=\"center\">\r\n");
      out.write(" \r\n");
      out.write("  <h5>Please contact to the owner of a file to get File Tag</h5>\r\n");
      out.write("  <div class=\"panel panel-default\" style=\"width: 50%\">\r\n");
      out.write("    <div class=\"panel-heading\"><h4>Enter File Tag</h4></div>\r\n");
      out.write("    <div class=\"panel-body\">\r\n");
      out.write("    <form action=\"OtherFileDownload\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"text\" name=\"key\" class=\"form-control\" placeholder=\"Enter File Tag here\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"filename\" value=\"");
      out.print(filename);
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"filepath\" value=\"");
      out.print(filePath);
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"hash\" value=\"");
      out.print(hash);
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"status\" value=\"");
      out.print(status);
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Download</button>\r\n");
      out.write("        <button type=\"reset\" class=\"btn btn-danger\">Reset</button>        \r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("<div>\r\n");
      out.write("	<footer id=\"footer\">\r\n");
      out.write("		<div class=\"footer2\" style=\"background-color: black;height: 60px; margin-bottom: 00px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"panel-body\">\r\n");
      out.write("							<p align=\"center\">\r\n");
      out.write("								Copyright &copy; 2015-16.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("</div>\r\n");

}

      out.write("\r\n");
      out.write("	<script src=\"assets/js/modernizr-latest.js\"></script>\r\n");
      out.write("	<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.cslider.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
