/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-03-03 15:16:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.deduplication.db.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.deduplication.db");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>View Your Profile Here</title>\r\n");
      out.write("<link rel=\"favicon\" href=\"assets/images/favicon.png\">\r\n");
      out.write("	<link rel=\"stylesheet\" media=\"screen\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,700\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.css\" media=\"screen\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/da-slider.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\"src=\"https://maps.googleapis.com/maps/api/js?sensor=false\">\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String un=(String)session.getAttribute("userName");
	session.setAttribute("Username", un);

      out.write("\r\n");
      out.write("<div class=\"navbar navbar-inverse\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<h4 align=\"right\"> <font color=\"red\">Welcome ");
      out.print(session.getAttribute("userName"));
      out.write("</font></h4>\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("					DEDUPLICATION</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navbar-collapse collapse\">\r\n");
      out.write("				<ul class=\"nav navbar-nav pull-right mainNav\">\r\n");
      out.write("					<li class=\"active\"><a href=\"user_home.jsp\">Home</a></li>\r\n");
      out.write("					<li class=\"active\"><a href=\"file_upload.jsp\">Browse File</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"Own_files.jsp\">Own Files</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"View_files.jsp\">View Files</a></li>\r\n");
      out.write("			    	<li class=\"active\"><a href=\"Profile.jsp\">Setting</a></li>\r\n");
      out.write("					<li class=\"active\"><a href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("            </ul>        \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"margin-left: 25%;margin-right: 60px;width: 50%\" align=\"center\">\r\n");
      out.write("		");
 
        	Connection connection =ConnectionFactory.getInstance().getConnection();
            Statement statement = connection.createStatement();
          
            ResultSet resultset =statement.executeQuery("select * from user where Email='"+un+"'") ; 
            String name=null,email=null,contact=null,password=null;
			while(resultset.next())
             {
				name=resultset.getString(2);
				email=resultset.getString(3);
				contact=resultset.getString(5);
				password=resultset.getString(4);
             }	
        
      out.write("\r\n");
      out.write("        <TABLE class=\"table table-bordered\">\r\n");
      out.write("            <TR>\r\n");
      out.write("               <TH>Name</TH>\r\n");
      out.write("               <TD> ");
      out.print(name );
      out.write("</TD>\r\n");
      out.write("            </Tr>   \r\n");
      out.write("            <TR >\r\n");
      out.write("               <TH>Email</TH>\r\n");
      out.write("               <TD> ");
      out.print( email );
      out.write(" </TD>\r\n");
      out.write("            </TR>   \r\n");
      out.write("            <TR>\r\n");
      out.write("               <Th>Contact</Th>\r\n");
      out.write("               <TD> ");
      out.print( contact );
      out.write(" </TD>\r\n");
      out.write("             </tr>  \r\n");
      out.write("            <TR>\r\n");
      out.write("               <Th>Password</Th>\r\n");
      out.write("                <TD> ");
      out.print(password );
      out.write(" &nbsp;&nbsp;<button type=\"button\" name=\"Change\" class=\"btn btn-link\" data-toggle=\"modal\" data-target=\"#myModal\">Change</button> </TD>   \r\n");
      out.write("           	</TR>\r\n");
      out.write("         </TABLE>       \r\n");
      out.write("<div style=\"margin-right: 20px\" align=\"right\">\r\n");
      out.write("	<button type=\"button\" name=\"Change\" class=\"btn btn-info\" data-toggle=\"modal\" data-target=\"#myModal1\">Change Details</button> \r\n");
      out.write("</div>         \r\n");
      out.write("         <div class=\"modal fade\" id=\"myModal1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" style=\"width: 35%\">\r\n");
      out.write(" <form onsubmit=\"confirmchange()\" action=\"changedetails\" method=\"post\" autocomplete=\"off\">  \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\" style=\"background-color: gray;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\" align=\"center\">Change Account Details Here</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("		<select class=\"form-control\" name=\"change\">\r\n");
      out.write("			<option value=\"Name\">User Name</option>\r\n");
      out.write("        	<option value=\"Email\">Email</option>\r\n");
      out.write("        	<option value=\"Contact\">Contact</option>\r\n");
      out.write("		</select><br>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Enter New Value\" name=\"value\">\r\n");
      out.write("        </div>        \r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("        <button type=\"reset\" class=\"btn btn-danger\">Reset</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>              \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" style=\"width: 35%\">\r\n");
      out.write(" <form onsubmit=\"confirmchange()\" action=\"Change_password\" method=\"post\" autocomplete=\"off\">  \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\"  style=\"background-color: gray;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\" align=\"center\">Change Your Password Here</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" placeholder=\"Enter Old Password Here\" name=\"oldpassword\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Enter New Password Here\" name=\"password\" required pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" title=\"Password must contain at least 6 characters, including UPPER/lowercase and numbers.\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"confirmpassword\" placeholder=\"Confirm New Password\" name=\"confirmpassword\" required pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" title=\"Password must contain at least 6 characters, including UPPER/lowercase and numbers.\">\r\n");
      out.write("        </div>        \r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("        <button type=\"reset\" class=\"btn btn-danger\">Reset</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>              \r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("<div>\r\n");
      out.write("	<footer id=\"footer\">\r\n");
      out.write("		<div class=\"footer2\" style=\"background-color: black;height: 75px; margin-bottom: 00px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"panel-body\">\r\n");
      out.write("							<p align=\"center\">\r\n");
      out.write("								Copyright &copy; 2015-16.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("</div>\r\n");
      out.write("	<script src=\"assets/js/modernizr-latest.js\"></script>\r\n");
      out.write("	<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.cslider.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    var password = document.getElementById(\"password\")\r\n");
      out.write("  	  , confirm_password = document.getElementById(\"confirmpassword\");\r\n");
      out.write("\r\n");
      out.write("  	function validatePassword(){\r\n");
      out.write("  	  if(password.value != confirm_password.value) {\r\n");
      out.write("  	    confirm_password.setCustomValidity(\"Passwords Don't Match\");\r\n");
      out.write("  	  } else {\r\n");
      out.write("  	    confirm_password.setCustomValidity('');\r\n");
      out.write("  	  }\r\n");
      out.write("  	}\r\n");
      out.write("  	password.onchange = validatePassword;\r\n");
      out.write("  	confirm_password.onkeyup = validatePassword;\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("function confirmchange() \r\n");
      out.write("{ \r\n");
      out.write(" return confirm(\"Are you sure you want to change?\");   \r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
