/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-03-03 15:05:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fsignin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>Deduplication</title>\r\n");
      out.write("	<link rel=\"favicon\" href=\"assets1/images/favicon.png\">\r\n");
      out.write("	<link rel=\"stylesheet\" media=\"screen\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,700\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets1/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets1/css/font-awesome.min.css\">\r\n");
      out.write("	<!-- Custom styles for our template -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets1/css/bootstrap-theme.css\" media=\"screen\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"assets1/css/da-slider.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets1/css/style.css\">\r\n");
      out.write("	<script src=\"assets1/js/html5shiv.js\"></script>\r\n");
      out.write("	<script src=\"assets1/js/respond.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  	<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"navbar navbar-inverse\" style=\"background-color: black;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<!-- Button for smallest screens -->\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"Index.jsp\">\r\n");
      out.write("				<h4>DEDUPLICATION</h4>\r\n");
      out.write("				</a>	\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navbar-collapse collapse\">\r\n");
      out.write("				<ul class=\"nav navbar-nav pull-right mainNav\">\r\n");
      out.write("					<li><a href=\"Index.jsp\">Home</a></li>\r\n");
      out.write("					<li><a href=\"user_signin.jsp\">User</a></li>\r\n");
      out.write("					<li><a href=\"admin_signin.jsp\">Admin</a></li>\r\n");
      out.write("					<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--/.nav-collapse -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>  \r\n");
      out.write("<div align=\"center\" style=\"margin-top: 30px\" id=\"login\">\r\n");
      out.write("<div  style=\"width: 35%\" >\r\n");
      out.write("    <div class=\"panel panel-primary\">\r\n");
      out.write("		<div class=\"panel-heading\" align=\"center\">Login Form</div>\r\n");
      out.write("		<div class=\"panel-body\">\r\n");
      out.write("    <form action=\"Usersignin\" method=\"post\">\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">    \r\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"inputEmail\" placeholder=\"Email ID\" name=\"email\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Password\" name=\"password\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"checkbox\" align=\"left\">\r\n");
      out.write("            <label><input type=\"checkbox\"> Remember me</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Login</button>\r\n");
      out.write("         <button type=\"reset\" class=\"btn btn-primary\">Reset</button><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div align=\"right\">\r\n");
      out.write("         Forgot Password:        <button type=\"button\" class=\"btn btn-link\" data-toggle=\"modal\" data-target=\"#myModal1\">Click Here</button> \r\n");
      out.write("        </div> \r\n");
      out.write("         \r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        New Member:  <button type=\"button\" class=\"btn btn-link\" data-toggle=\"modal\" data-target=\"#myModal\">Sign Up</button>        \r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" style=\"width: 35%\">\r\n");
      out.write("    <form onsubmit=\"confirmreg()\" action=\"Usersignup\" method=\"post\" autocomplete=\"off\"> \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\"  style=\"background-color: gray;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">Registration Page</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("         <div class=\"form-group\" align=\"left\">\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" name=\"name\" placeholder=\"Your Name\" required pattern=\"[a-zA-Z\\s]+\" title=\"Enter Your Name(eg.abc)\">\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" placeholder=\"Email ID\" name=\"email\" required pattern=\".*@gmail\\.com\" title=\"Enter your email (abc@gmail.com)\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"passwordsignup\" placeholder=\"Password\" name=\"password\" required pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" title=\"Password must contain at least 6 characters, including UPPER/lowercase and numbers.\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"passwordsignup_confirm\" placeholder=\"Confirm Password\"  required pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" title=\"Password must contain at least 6 characters, including UPPER/lowercase and numbers.\">\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Mobile No\" name=\"Contact\" required pattern=\"[7-9]{1}[0-9]{9}\"  title=\"* Mobile number with 7-9 and remaing 9 digit with 0-9\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Sign Up</button>\r\n");
      out.write("         <button type=\"reset\" class=\"btn btn-primary\">Reset</button><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" style=\"width: 35%\">\r\n");
      out.write(" <form action=\"Mailcheck\" method=\"post\" autocomplete=\"off\"> \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\"  style=\"background-color: gray;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\" align=\"center\">Enter Your Email ID To get Password</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"form-group\" align=\"left\">\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"inputEmail\" placeholder=\"Email ID\" name=\"email\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br>\r\n");
      out.write("	\r\n");
      out.write("	<footer id=\"footer\">\r\n");
      out.write("			\r\n");
      out.write("		<div class=\"footer2\" style=\"height: 42px\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("<script>\r\n");
      out.write("    var password = document.getElementById(\"passwordsignup\")\r\n");
      out.write("  	  , confirm_password = document.getElementById(\"passwordsignup_confirm\");\r\n");
      out.write("\r\n");
      out.write("  	function validatePassword(){\r\n");
      out.write("  	  if(password.value != confirm_password.value) {\r\n");
      out.write("  	    confirm_password.setCustomValidity(\"Passwords Don't Match\");\r\n");
      out.write("  	  } else {\r\n");
      out.write("  	    confirm_password.setCustomValidity('');\r\n");
      out.write("  	  }\r\n");
      out.write("  	}\r\n");
      out.write("\r\n");
      out.write("  	password.onchange = validatePassword;\r\n");
      out.write("  	confirm_password.onkeyup = validatePassword;\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("function confirmreg() \r\n");
      out.write("{ \r\n");
      out.write(" return confirm(\"Are you sure you want to Register?\");   \r\n");
      out.write("} \r\n");
      out.write("	<script src=\"assets1/js/modernizr-latest.js\"></script>\r\n");
      out.write("	<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"assets1/js/jquery.cslider.js\"></script>\r\n");
      out.write("	<script src=\"assets1/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
